AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
  TargetRubyVersion: 2.4
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'shared_examples']
  Exclude:
    - 'config/routes.rb'